AllCops:
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
  RunRailsCops: true

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
